export const coin_info_data = [
	{
		id: "bitcoin",
		image: "https://coin-images.coingecko.com/coins/images/1/large/bitcoin.png?1696501400",
		name: "Bitcoin",
		symbol: "btc",
	},
	{
		id: "ethereum",
		image: "https://coin-images.coingecko.com/coins/images/279/large/ethereum.png?1696501628",
		name: "Ethereum",
		symbol: "eth",
	},
	{
		id: "tether",
		image: "https://coin-images.coingecko.com/coins/images/325/large/Tether.png?1696501661",
		name: "Tether",
		symbol: "usdt",
	},
	{
		id: "binancecoin",
		image: "https://coin-images.coingecko.com/coins/images/825/large/bnb-icon2_2x.png?1696501970",
		name: "BNB",
		symbol: "bnb",
	},
	{
		id: "solana",
		image: "https://coin-images.coingecko.com/coins/images/4128/large/solana.png?1696504756",
		name: "Solana",
		symbol: "sol",
	},
	{
		id: "staked-ether",
		image: "https://coin-images.coingecko.com/coins/images/13442/large/steth_logo.png?1696513206",
		name: "Lido Staked Ether",
		symbol: "steth",
	},
	{
		id: "usd-coin",
		image: "https://coin-images.coingecko.com/coins/images/6319/large/usdc.png?1696506694",
		name: "USDC",
		symbol: "usdc",
	},
	{
		id: "ripple",
		image: "https://coin-images.coingecko.com/coins/images/44/large/xrp-symbol-white-128.png?1696501442",
		name: "XRP",
		symbol: "xrp",
	},
	{
		id: "dogecoin",
		image: "https://coin-images.coingecko.com/coins/images/5/large/dogecoin.png?1696501409",
		name: "Dogecoin",
		symbol: "doge",
	},
	{
		id: "the-open-network",
		image: "https://coin-images.coingecko.com/coins/images/17980/large/ton_symbol.png?1696517498",
		name: "Toncoin",
		symbol: "ton",
	},
	{
		id: "cardano",
		image: "https://coin-images.coingecko.com/coins/images/975/large/cardano.png?1696502090",
		name: "Cardano",
		symbol: "ada",
	},
	{
		id: "shiba-inu",
		image: "https://coin-images.coingecko.com/coins/images/11939/large/shiba.png?1696511800",
		name: "Shiba Inu",
		symbol: "shib",
	},
	{
		id: "avalanche-2",
		image: "https://coin-images.coingecko.com/coins/images/12559/large/Avalanche_Circle_RedWhite_Trans.png?1696512369",
		name: "Avalanche",
		symbol: "avax",
	},
	{
		id: "wrapped-bitcoin",
		image: "https://coin-images.coingecko.com/coins/images/7598/large/wrapped_bitcoin_wbtc.png?1696507857",
		name: "Wrapped Bitcoin",
		symbol: "wbtc",
	},
	{
		id: "chainlink",
		image: "https://coin-images.coingecko.com/coins/images/877/large/chainlink-new-logo.png?1696502009",
		name: "Chainlink",
		symbol: "link",
	},
	{
		id: "tron",
		image: "https://coin-images.coingecko.com/coins/images/1094/large/tron-logo.png?1696502193",
		name: "TRON",
		symbol: "trx",
	},
	{
		id: "polkadot",
		image: "https://coin-images.coingecko.com/coins/images/12171/large/polkadot.png?1696512008",
		name: "Polkadot",
		symbol: "dot",
	},
	{
		id: "bitcoin-cash",
		image: "https://coin-images.coingecko.com/coins/images/780/large/bitcoin-cash-circle.png?1696501932",
		name: "Bitcoin Cash",
		symbol: "bch",
	},
	{
		id: "near",
		image: "https://coin-images.coingecko.com/coins/images/10365/large/near.jpg?1696510367",
		name: "NEAR Protocol",
		symbol: "near",
	},
	{
		id: "uniswap",
		image: "https://coin-images.coingecko.com/coins/images/12504/large/uni.jpg?1696512319",
		name: "Uniswap",
		symbol: "uni",
	},
	{
		id: "matic-network",
		image: "https://coin-images.coingecko.com/coins/images/4713/large/polygon.png?1698233745",
		name: "Polygon",
		symbol: "matic",
	},
	{
		id: "litecoin",
		image: "https://coin-images.coingecko.com/coins/images/2/large/litecoin.png?1696501400",
		name: "Litecoin",
		symbol: "ltc",
	},
	{
		id: "pepe",
		image: "https://coin-images.coingecko.com/coins/images/29850/large/pepe-token.jpeg?1696528776",
		name: "Pepe",
		symbol: "pepe",
	},
	{
		id: "internet-computer",
		image: "https://coin-images.coingecko.com/coins/images/14495/large/Internet_Computer_logo.png?1696514180",
		name: "Internet Computer",
		symbol: "icp",
	},
	{
		id: "wrapped-eeth",
		image: "https://coin-images.coingecko.com/coins/images/33033/large/weETH.png?1701438396",
		name: "Wrapped eETH",
		symbol: "weeth",
	},
	{
		id: "leo-token",
		image: "https://coin-images.coingecko.com/coins/images/8418/large/leo-token.png?1696508607",
		name: "LEO Token",
		symbol: "leo",
	},
	{
		id: "fetch-ai",
		image: "https://coin-images.coingecko.com/coins/images/5681/large/Fetch.jpg?1696506140",
		name: "Fetch.ai",
		symbol: "fet",
	},
	{
		id: "dai",
		image: "https://coin-images.coingecko.com/coins/images/9956/large/Badge_Dai.png?1696509996",
		name: "Dai",
		symbol: "dai",
	},
	{
		id: "ethereum-classic",
		image: "https://coin-images.coingecko.com/coins/images/453/large/ethereum-classic-logo.png?1696501717",
		name: "Ethereum Classic",
		symbol: "etc",
	},
	{
		id: "kaspa",
		image: "https://coin-images.coingecko.com/coins/images/25751/large/kaspa-icon-exchanges.png?1696524837",
		name: "Kaspa",
		symbol: "kas",
	},
	{
		id: "render-token",
		image: "https://coin-images.coingecko.com/coins/images/11636/large/rndr.png?1696511529",
		name: "Render",
		symbol: "rndr",
	},
	{
		id: "aptos",
		image: "https://coin-images.coingecko.com/coins/images/26455/large/aptos_round.png?1696525528",
		name: "Aptos",
		symbol: "apt",
	},
	{
		id: "renzo-restaked-eth",
		image: "https://coin-images.coingecko.com/coins/images/34753/large/Ezeth_logo_circle.png?1713496404",
		name: "Renzo Restaked ETH",
		symbol: "ezeth",
	},
	{
		id: "hedera-hashgraph",
		image: "https://coin-images.coingecko.com/coins/images/3688/large/hbar.png?1696504364",
		name: "Hedera",
		symbol: "hbar",
	},
	{
		id: "blockstack",
		image: "https://coin-images.coingecko.com/coins/images/2069/large/Stacks_Logo_png.png?1709979332",
		name: "Stacks",
		symbol: "stx",
	},
	{
		id: "filecoin",
		image: "https://coin-images.coingecko.com/coins/images/12817/large/filecoin.png?1696512609",
		name: "Filecoin",
		symbol: "fil",
	},
	{
		id: "cosmos",
		image: "https://coin-images.coingecko.com/coins/images/1481/large/cosmos_hub.png?1696502525",
		name: "Cosmos Hub",
		symbol: "atom",
	},
	{
		id: "mantle",
		image: "https://coin-images.coingecko.com/coins/images/30980/large/token-logo.png?1696529819",
		name: "Mantle",
		symbol: "mnt",
	},
	{
		id: "dogwifcoin",
		image: "https://coin-images.coingecko.com/coins/images/33566/large/dogwifhat.jpg?1702499428",
		name: "dogwifhat",
		symbol: "wif",
	},
	{
		id: "immutable-x",
		image: "https://coin-images.coingecko.com/coins/images/17233/large/immutableX-symbol-BLK-RGB.png?1696516787",
		name: "Immutable",
		symbol: "imx",
	},
	{
		id: "arbitrum",
		image: "https://coin-images.coingecko.com/coins/images/16547/large/photo_2023-03-29_21.47.00.jpeg?1696516109",
		name: "Arbitrum",
		symbol: "arb",
	},
	{
		id: "ethena-usde",
		image: "https://coin-images.coingecko.com/coins/images/33613/large/USDE.png?1716355685",
		name: "Ethena USDe",
		symbol: "usde",
	},
	{
		id: "stellar",
		image: "https://coin-images.coingecko.com/coins/images/100/large/Stellar_symbol_black_RGB.png?1696501482",
		name: "Stellar",
		symbol: "xlm",
	},
	{
		id: "crypto-com-chain",
		image: "https://coin-images.coingecko.com/coins/images/7310/large/cro_token_logo.png?1696507599",
		name: "Cronos",
		symbol: "cro",
	},
	{
		id: "floki",
		image: "https://coin-images.coingecko.com/coins/images/16746/large/PNG_image.png?1696516318",
		name: "FLOKI",
		symbol: "floki",
	},
	{
		id: "monero",
		image: "https://coin-images.coingecko.com/coins/images/69/large/monero_logo.png?1696501460",
		name: "Monero",
		symbol: "xmr",
	},
	{
		id: "okb",
		image: "https://coin-images.coingecko.com/coins/images/4463/large/WeChat_Image_20220118095654.png?1696505053",
		name: "OKB",
		symbol: "okb",
	},
	{
		id: "bittensor",
		image: "https://coin-images.coingecko.com/coins/images/28452/large/ARUsPeNQ_400x400.jpeg?1696527447",
		name: "Bittensor",
		symbol: "tao",
	},
	{
		id: "first-digital-usd",
		image: "https://coin-images.coingecko.com/coins/images/31079/large/firstfigital.jpeg?1696529912",
		name: "First Digital USD",
		symbol: "fdusd",
	},
	{
		id: "the-graph",
		image: "https://coin-images.coingecko.com/coins/images/13397/large/Graph_Token.png?1696513159",
		name: "The Graph",
		symbol: "grt",
	},
	{
		id: "arweave",
		image: "https://coin-images.coingecko.com/coins/images/4343/large/oRt6SiEN_400x400.jpg?1696504946",
		name: "Arweave",
		symbol: "ar",
	},
	{
		id: "optimism",
		image: "https://coin-images.coingecko.com/coins/images/25244/large/Optimism.png?1696524385",
		name: "Optimism",
		symbol: "op",
	},
	{
		id: "sui",
		image: "https://coin-images.coingecko.com/coins/images/26375/large/sui_asset.jpeg?1696525453",
		name: "Sui",
		symbol: "sui",
	},
	{
		id: "injective-protocol",
		image: "https://coin-images.coingecko.com/coins/images/12882/large/Secondary_Symbol.png?1696512670",
		name: "Injective",
		symbol: "inj",
	},
	{
		id: "vechain",
		image: "https://coin-images.coingecko.com/coins/images/1167/large/VET_Token_Icon.png?1710013505",
		name: "VeChain",
		symbol: "vet",
	},
	{
		id: "maker",
		image: "https://coin-images.coingecko.com/coins/images/1364/large/Mark_Maker.png?1696502423",
		name: "Maker",
		symbol: "mkr",
	},
	{
		id: "fantom",
		image: "https://coin-images.coingecko.com/coins/images/4001/large/Fantom_round.png?1696504642",
		name: "Fantom",
		symbol: "ftm",
	},
	{
		id: "notcoin",
		image: "https://coin-images.coingecko.com/coins/images/33453/large/rFmThDiD_400x400.jpg?1701876350",
		name: "Notcoin",
		symbol: "not",
	},
	{
		id: "theta-token",
		image: "https://coin-images.coingecko.com/coins/images/2538/large/theta-token-logo.png?1696503349",
		name: "Theta Network",
		symbol: "theta",
	},
	{
		id: "bonk",
		image: "https://coin-images.coingecko.com/coins/images/28600/large/bonk.jpg?1696527587",
		name: "Bonk",
		symbol: "bonk",
	},
	{
		id: "rocket-pool-eth",
		image: "https://coin-images.coingecko.com/coins/images/20764/large/reth.png?1696520159",
		name: "Rocket Pool ETH",
		symbol: "reth",
	},
	{
		id: "thorchain",
		image: "https://coin-images.coingecko.com/coins/images/6595/large/Rune200x200.png?1696506946",
		name: "THORChain",
		symbol: "rune",
	},
	{
		id: "ondo-finance",
		image: "https://coin-images.coingecko.com/coins/images/26580/large/ONDO.png?1696525656",
		name: "Ondo",
		symbol: "ondo",
	},
	{
		id: "lido-dao",
		image: "https://coin-images.coingecko.com/coins/images/13573/large/Lido_DAO.png?1696513326",
		name: "Lido DAO",
		symbol: "ldo",
	},
	{
		id: "celestia",
		image: "https://coin-images.coingecko.com/coins/images/31967/large/tia.jpg?1696530772",
		name: "Celestia",
		symbol: "tia",
	},
	{
		id: "jasmycoin",
		image: "https://coin-images.coingecko.com/coins/images/13876/large/JASMY200x200.jpg?1696513620",
		name: "JasmyCoin",
		symbol: "jasmy",
	},
	{
		id: "mantle-staked-ether",
		image: "https://coin-images.coingecko.com/coins/images/33345/large/symbol_transparent_bg.png?1701697066",
		name: "Mantle Staked Ether",
		symbol: "meth",
	},
	{
		id: "coredaoorg",
		image: "https://coin-images.coingecko.com/coins/images/28938/large/file_589.jpg?1701868471",
		name: "Core",
		symbol: "core",
	},
	{
		id: "pyth-network",
		image: "https://coin-images.coingecko.com/coins/images/31924/large/pyth.png?1701245725",
		name: "Pyth Network",
		symbol: "pyth",
	},
	{
		id: "starknet",
		image: "https://coin-images.coingecko.com/coins/images/26433/large/starknet.png?1696525507",
		name: "Starknet",
		symbol: "strk",
	},
	{
		id: "bitget-token",
		image: "https://coin-images.coingecko.com/coins/images/11610/large/icon_colour.png?1696511504",
		name: "Bitget Token",
		symbol: "bgb",
	},
	{
		id: "eos",
		image: "https://coin-images.coingecko.com/coins/images/738/large/eos-eos-logo.png?1696501893",
		name: "EOS",
		symbol: "eos",
	},
	{
		id: "gala",
		image: "https://coin-images.coingecko.com/coins/images/12493/large/GALA_token_image_-_200PNG.png?1709725869",
		name: "GALA",
		symbol: "gala",
	},
	{
		id: "ethena",
		image: "https://coin-images.coingecko.com/coins/images/36530/large/ethena.png?1711701436",
		name: "Ethena",
		symbol: "ena",
	},
	{
		id: "aave",
		image: "https://coin-images.coingecko.com/coins/images/12645/large/AAVE.png?1696512452",
		name: "Aave",
		symbol: "aave",
	},
	{
		id: "jupiter-exchange-solana",
		image: "https://coin-images.coingecko.com/coins/images/34188/large/jup.png?1704266489",
		name: "Jupiter",
		symbol: "jup",
	},
	{
		id: "algorand",
		image: "https://coin-images.coingecko.com/coins/images/4380/large/download.png?1696504978",
		name: "Algorand",
		symbol: "algo",
	},
	{
		id: "sei-network",
		image: "https://coin-images.coingecko.com/coins/images/28205/large/Sei_Logo_-_Transparent.png?1696527207",
		name: "Sei",
		symbol: "sei",
	},
	{
		id: "whitebit",
		image: "https://coin-images.coingecko.com/coins/images/27045/large/wbt_token.png?1696526096",
		name: "WhiteBIT Coin",
		symbol: "wbt",
	},
	{
		id: "flow",
		image: "https://coin-images.coingecko.com/coins/images/13446/large/5f6294c0c7a8cda55cb1c936_Flow_Wordmark.png?1696513210",
		name: "Flow",
		symbol: "flow",
	},
	{
		id: "based-brett",
		image: "https://coin-images.coingecko.com/coins/images/35529/large/1000050750.png?1709031995",
		name: "Brett",
		symbol: "brett",
	},
	{
		id: "beam-2",
		image: "https://coin-images.coingecko.com/coins/images/32417/large/chain-logo.png?1698114384",
		name: "Beam",
		symbol: "beam",
	},
	{
		id: "quant-network",
		image: "https://coin-images.coingecko.com/coins/images/3370/large/5ZOu7brX_400x400.jpg?1696504070",
		name: "Quant",
		symbol: "qnt",
	},
	{
		id: "flare-networks",
		image: "https://coin-images.coingecko.com/coins/images/28624/large/FLR-icon200x200.png?1696527609",
		name: "Flare",
		symbol: "flr",
	},
	{
		id: "chiliz",
		image: "https://coin-images.coingecko.com/coins/images/8834/large/CHZ_Token_updated.png?1696508986",
		name: "Chiliz",
		symbol: "chz",
	},
	{
		id: "bitcoin-cash-sv",
		image: "https://coin-images.coingecko.com/coins/images/6799/large/BSV.png?1696507128",
		name: "Bitcoin SV",
		symbol: "bsv",
	},
	{
		id: "axie-infinity",
		image: "https://coin-images.coingecko.com/coins/images/13029/large/axie_infinity_logo.png?1696512817",
		name: "Axie Infinity",
		symbol: "axs",
	},
	{
		id: "ordinals",
		image: "https://coin-images.coingecko.com/coins/images/30162/large/ordi.png?1696529082",
		name: "ORDI",
		symbol: "ordi",
	},
	{
		id: "dydx-chain",
		image: "https://coin-images.coingecko.com/coins/images/32594/large/dydx.png?1698673495",
		name: "dYdX",
		symbol: "dydx",
	},
	{
		id: "cheelee",
		image: "https://coin-images.coingecko.com/coins/images/28573/large/CHEEL_%D1%82%D0%BE%D0%BD%D0%BA%D0%B0%D1%8F_%D0%BE%D0%B1%D0%B2%D0%BE%D0%B4%D0%BA%D0%B0_%283%29.png?1696527561",
		name: "Cheelee",
		symbol: "cheel",
	},
	{
		id: "zebec-protocol",
		image: "https://coin-images.coingecko.com/coins/images/24342/large/zebec.jpeg?1696523526",
		name: "Zebec Protocol",
		symbol: "zbc",
	},
	{
		id: "worldcoin-wld",
		image: "https://coin-images.coingecko.com/coins/images/31069/large/worldcoin.jpeg?1696529903",
		name: "Worldcoin",
		symbol: "wld",
	},
	{
		id: "kelp-dao-restaked-eth",
		image: "https://coin-images.coingecko.com/coins/images/33800/large/Icon___Dark.png?1702991855",
		name: "Kelp DAO Restaked ETH",
		symbol: "rseth",
	},
	{
		id: "gatechain-token",
		image: "https://coin-images.coingecko.com/coins/images/8183/large/gate.png?1696508395",
		name: "Gate",
		symbol: "gt",
	},
	{
		id: "singularitynet",
		image: "https://coin-images.coingecko.com/coins/images/2138/large/singularitynet.png?1696503103",
		name: "SingularityNET",
		symbol: "agix",
	},
	{
		id: "bittorrent",
		image: "https://coin-images.coingecko.com/coins/images/22457/large/btt_logo.png?1696521780",
		name: "BitTorrent",
		symbol: "btt",
	},
	{
		id: "wormhole",
		image: "https://coin-images.coingecko.com/coins/images/35087/large/womrhole_logo_full_color_rgb_2000px_72ppi_fb766ac85a.png?1708688954",
		name: "Wormhole",
		symbol: "w",
	},
	{
		id: "akash-network",
		image: "https://coin-images.coingecko.com/coins/images/12785/large/akash-logo.png?1696512580",
		name: "Akash Network",
		symbol: "akt",
	},
	{
		id: "elrond-erd-2",
		image: "https://coin-images.coingecko.com/coins/images/12335/large/egld-token-logo.png?1696512162",
		name: "MultiversX",
		symbol: "egld",
	},
	{
		id: "tokenize-xchange",
		image: "https://coin-images.coingecko.com/coins/images/4984/large/TKX_-_Logo_-_RGB-15.png?1696505519",
		name: "Tokenize Xchange",
		symbol: "tkx",
	},
]

export const fiat_info_data = [
	{
		currency: "NGN",
		image: "https://countryflagsapi.netlify.app/flag/NG.svg",
		name: "Nigerian Naira",
	},
	{
		currency: "USD",
		image: "https://countryflagsapi.netlify.app/flag/US.svg",
		name: "United States Dollars",
	},
	{
		currency: "GHS",
		image: "https://countryflagsapi.netlify.app/flag/GH.svg",
		name: "Ghanian Cedis",
	},
	{
		currency: "ZAR",
		image: "https://countryflagsapi.netlify.app/flag/ZA.svg",
		name: "South African Rand",
	},
	{
		currency: "KES",
		image: "https://countryflagsapi.netlify.app/flag/KE.svg",
		name: "Kenyan Shillings",
	},
]

export function getCryptoCoinInfoData(symbol: string) {
	return coin_info_data?.find((data) => data.symbol?.toLowerCase() === symbol?.toLowerCase())
}

export function getFiatCurrencyInfoData(currency: string) {
	return fiat_info_data?.find((data) => data.currency?.toLowerCase() === currency?.toLowerCase())
}
