import { ADMIN_ACCESS_LEVELS } from "@utils/enum"


export const ADMIN_ACCESS_LEVELS_HIERARCHY: { [key in ADMIN_ACCESS_LEVELS]: number } = {
	[ADMIN_ACCESS_LEVELS.VIEWER]: 0,
	[ADMIN_ACCESS_LEVELS.ADMIN]: 1,
	[ADMIN_ACCESS_LEVELS.SUPER_ADMIN]: 2,

}
